In [1]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print (x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2, 5])

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
y

tensor([[0.4772, 0.7624, 0.1441, 0.5556, 0.3480],
        [0.9280, 0.9293, 0.5851, 0.0477, 0.3492]])

In [6]:
y.view([1,10])

tensor([[0.4772, 0.7624, 0.1441, 0.5556, 0.3480, 0.9280, 0.9293, 0.5851, 0.0477,
         0.3492]])

In [7]:
y

tensor([[0.4772, 0.7624, 0.1441, 0.5556, 0.3480],
        [0.9280, 0.9293, 0.5851, 0.0477, 0.3492]])

In [8]:
y = y.view([1,10])

In [9]:
y

tensor([[0.4772, 0.7624, 0.1441, 0.5556, 0.3480, 0.9280, 0.9293, 0.5851, 0.0477,
         0.3492]])